version: 0.2

env:
 parameter-store:
    DOCKER_USERNAME: username
    DOCKER_PASSWORD: password

phases:
  pre_build:
    commands:
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - docker pull node:14
      - echo "Sucess docker login && pull node"
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 871724687805.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo "sucess login"
      - docker build -t weather .
      - echo "Happly build the dockerfile"
      - docker tag weather:latest 871724687805.dkr.ecr.ap-south-1.amazonaws.com/weather:latest
      - ls -la
  post_build:
     commands:
       - echo "Enter post_build"
       - echo build start on  `date`
       - docker push 871724687805.dkr.ecr.ap-south-1.amazonaws.com/weather:latest
       - echo Writing image definition file..
       - printf '[{"name":"projectk","imageUri":"871724687805.dkr.ecr.ap-south-1.amazonaws.com/weather:latest"}]' > imagedefinitions.json
artifacts:
     files: imagedefinitions.json
